### ISSUE TITLE
What is the technique used to accumulate function arguments?

### ISSUE THREAD

**Issue by mrakgr** [rspeele/FParsec-Pipes#2]
You probably know what I mean:

```
let num: Parser<int,unit> =
    %% +.digits 1 -- +.digits 2 -- +.digits 3 -- +.digits 4 -- +.digits 5 -- +.digits 6 -- +.digits 7
    -%> fun a b c d e f g -> f
```

I've been studying the library for a while now and though I'd ask how is it possible to get that precise `-%> fun a b c d e f g -> f` dependent on the parsers used previously without pattern matching on tuples like in Fparsec?

Actually, I was sure being able to take the correct number of arguments at the end as if accumulating them would be something impossible in F#, but you proved me wrong. Of course, I've been studying the code, but it is not really obvious what is happening there and I am not sure how to come up with a minimalist example. I would not mind if you gave me a pointer. Thanks!

Edit: Actually, what the `linkBeyond5` example does just dawned on me. It is similar to this:

```
let a = "asd"
let b = 2
let c = 'a'

let w = a |> (fun a b c -> c)
let e = b |> w
let r = c |> e
```

But still, the Pipes library takes all the arguments at the end, not at the start. How is that possible?

Edit2: I figured this out too. I asked because I thought I would not be able to do it, but I guess I did.

```
let a = "asd"
let b = 2
let c = 'a'

let w f = a |> f
let e f = b |> w f
let r f = c |> e f

r (fun a b c -> c)
```

You just pass in an argument acting as an accumulator. This does not explain everything, but now I understand what Pipes is doing. I feel like I have a firm basis now. Thanks for the novel idea. I'll definitely be using Pipes to write the parser I am about to do.

**Comment by rspeele** [comment]
Hi,

I'm happy to see somebody take an interest in this project, and even happier to see that you appreciate the trick of the pipe syntax, which I spent quite some time arguing with the compiler about.

I ought to do a better job explaining how the pipes work in the documentation, instead of just describing how the operators are used. To me, the hard part is `IPipeLink`, and `Pipe` is just a way of flipping it so that left-associative operators can be used (although `Pipe` is where the generic type parameters get really messy). Maybe if I write a `linkBeyond2` for documentation purposes that would help make it more clear for future visitors.

Anyway, since you mentioned that you are actually planning on using the library, I must warn you that the compile times suffer on large parsers. The slowdown comes not from the Pipes.fs code, but from all the overloaded operators and inline functions used to produce default parsers and other syntactic niceties. The Examples.SQLite parser I recently wrote is unusually large, so it's an extreme example, but it takes 25 seconds to compile on my home PC.

I use FParsec-Pipes in two projects, one at my workplace and one I'm currently developing in my spare time, and so far I have accepted the long compile times as the cost of nicer looking parser source code. However, your interest has motivated me to see what can be done about the problem. I believe I can cut compilation times down by 30% or so just by narrowing the type signatures of a few inline functions.

**Comment by mrakgr** [comment]
Thanks for the warning. Actually, I am writing a ML library and this did make me consider that I should replace inline functions with interfaces. It does not take an extreme time to compile, but it is longer than what I'd want.

Last night I did some more simplifications and came up with a monadic example, but in the end I realized that the above is pretty much equivalent to this:

``` fsharp
let u f = f a <| b <| c
u (fun a b c -> c)
```

If I am right, there is probably no real need for link 2-5 in `Pipes.fs`. Because they existed, at first I thought the library was nesting closures, but that can't possibly be.

**Comment by rspeele** [comment]
You are correct. `link1` could have this definition for `LinkUp` and link2-5 could be deleted.

```
member __.LinkUp up = linkBeyond5 (link1 up) (a |>> (|>))
```

However, in F# there's a measurable performance advantage to taking advantage of pipe functions dedicated to a specific arity. If you write a parser that captures four `pstring`s and concatenates them, the parser will run about twice as slow with the above definition (which builds three nested `pipe2`s instead of one `pipe4`). I would guess this is mainly due to the overhead of applying functions in curried form instead of via `FSharpFunc.InvokeFast`.

I have no ML experience to say whether this optimization makes sense there, so I recommend benchmarking it to decide the best approach for your library. (edit: It occurs to me that you may mean ML as in machine learning not ML as in standard ML -- I had assumed the latter).

**Comment by rspeele** [comment]
I've just published a new version that compiles upwards of 3x faster than the old one. There are a couple minor breaking changes to the API, which I note in issue #3 .

Interestingly, there is also a new "feature" of dubious utility, which is that the default parser for an `'a list` is now always a choice between the default parsers for the `'a`s in the list, if they have default parsers. This works even in nested cases like a `char list list list`, meaning that the prefix operator `%` is now a sort of recursive inline function whose base case is determined by type. I remember trying to make this work in F# in the past and failing, and this time I practically stumbled into it.

I apologize for accepting your pull request then immediately stomping over the code it affected. I still appreciate the gesture!

**Comment by mrakgr** [comment]
No problem, it was just a one letter typo fix. It is quite impressive that you managed to improve it this far. I'll have a look at the changes.

**Comment by mrakgr** [comment]
I went over it. Just by looking at it, I find that I do not have a good grasp why compilation times have improved, but nevermind that. 

> Use (qty.[count] \* parser) instead, which now returns an array rather than a ResizeArray.

You wrote the above in #3, but I am guessing you meant the reverse as `qty` functions still return ResizeArrays.

Edit: `qty.[x] * p` does in fact return a plain array as it uses the `ExactRange` class. 

I see. 

Ignore the above, though I'd suggest highlighting this in the documentation as `qty.[x..x]` and `qty.[x]` are no longer the same thing.

By the way, I really appreciate that you took the time to make these array parsers. A few week ago, I literally dropped Haskell - the entire language - because how frustrating doing something as simple like loading 100M integers into an array was. Lists, space leaks, the type system preventing me from fixing things...I ran into it all. And no parser combinator library used arrays anywhere. It is an insane language.

So I am writing that multidimensional array parser in F# now and it will be a part of a larger project that I am doing. It is really a breath of fresh air to find a functional parser library with enough sense to have parsers that use arrays internally.
