### ISSUE TITLE
Type annotation required for first intro example

### ISSUE THREAD

**Issue by mtnrbq** [rspeele/FParsec-Pipes#5]
I was having issues with the intro code in VSCode on Windows with the Ionide plugin.

Specifically:
`// Parses `count` digits and returns the result as an integer.
let digits (count : int) =
    %% +.(qty.[count] * digit)
    -%> (String >> Int32.Parse)` 
was complaining about the `(String >> Int32.Parse)` construct needing a type annotation to allow the String constructor to be resolved.

I ended up (after some assistance on fsharp slack) going with:
`let digits (count : int) =
    %% +.(qty.[count] * digit)
    -%> (fun (chars:char[]) -> String(chars) |> Int32.Parse )`

which worked for me

**Comment by rspeele** [comment]
Hi,

Thanks so much for reporting this, I never would've noticed.

`-%>` is overloaded so on its right side it can take either a function or `auto`. Originally I thought this was really cool, but using it heavily noticeably slows down the F# compiler.

Because of this, in my own parsers, I only use it for `-%> auto`, which isn't needed that often. The rest of the time I use `-|>` which is not overloaded. I've made some minor updates to the docs to reflect this. If you use `-|>` in this example I believe you won't need the extra type annotation.

At some point the example must've typechecked (or it wouldn't have gotten through FSharp.Formatting). I must've broken it while making other changes to try to improve compile times. But because overuse of `-%>` causes its own problems, I prefer to just advocate using `-|>` when passing anything except `auto` on the right.

Regards,
Robert

**Comment by mtnrbq** [comment]
Thanks for the update and the tip - great library to help make working with FParsec easier.
